# Generated by Django 4.2.8 on 2023-12-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='zou_field',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
